[package]
name = "evo"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
log = "0.4"
env_logger = "0.11.5"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
